

services:
  backend:
    build: ./server
    container_name: portfolio-backend
    ports:
      - "5000:4000"
    restart: unless-stopped
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    container_name: portfolio-frontend
    ports:
      - "8080:80"
    restart: always